name: Daily HackerNews
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  daily_hackernews:
    name: Daily HackerNews
    runs-on: ubuntu-latest
    steps:
      - name: daily-hackernews
        uses: actions/checkout@v1
        with:
          chat_id: "1077870607"
          coount: 5
        env:
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
