name: Daily HackerNews
on:
  schedule:
    - cron: 0 7 * * * # Every day at 7am
  watch:
    types: [started]

jobs:
  daily_hackernews:
    name: Daily HackerNews
    runs-on: ubuntu-latest
    steps:
      - name: daily-hackernews
        uses: jiyeonseo/daily-hackernews-action@v1.0
        with:
          chat_id: "1077870607"
          coount: 5
          telegram_key: ${{ secrets.TELEGRAM_KEY }}
